import { LanguageOption } from "./types";

export const GLOBAL_LANGUAGES: LanguageOption[] = [
  { label: "English", value: "en", flag: "gb" },
  { label: "Français", value: "fr", flag: "fr" },
  { label: "Español", value: "es", flag: "es" },
  { label: "Deutsch", value: "de", flag: "de" },
  { label: "Italiano", value: "it", flag: "it" },
  { label: "Português", value: "pt", flag: "pt" },
  { label: "Nederlands", value: "nl", flag: "nl" },
  { label: "Русский", value: "ru", flag: "ru" },
  { label: "简体中文", value: "zh-CN", flag: "cn" },
  { label: "繁體中文", value: "zh-TW", flag: "tw" },
  { label: "日本語", value: "ja", flag: "jp" },
  { label: "한국어", value: "ko", flag: "kr" },
  { label: "العربية", value: "ar", flag: "sa" },
  { label: "हिन्दी", value: "hi", flag: "in" },
  { label: "Türkçe", value: "tr", flag: "tr" },
  { label: "Tiếng Việt", value: "vi", flag: "vn" },
  { label: "Svenska", value: "sv", flag: "se" },
  { label: "Norsk", value: "no", flag: "no" },
  { label: "Dansk", value: "da", flag: "dk" },
  { label: "Suomi", value: "fi", flag: "fi" },
  { label: "Polski", value: "pl", flag: "pl" },
  { label: "Ελληνικά", value: "el", flag: "gr" },
  { label: "עברית", value: "he", flag: "il" },
  { label: "Bahasa Indonesia", value: "id", flag: "id" },
  { label: "Bahasa Melayu", value: "ms", flag: "my" },
  { label: "Română", value: "ro", flag: "ro" },
  { label: "Slovenčina", value: "sk", flag: "sk" },
  { label: "Čeština", value: "cs", flag: "cz" },
  { label: "Українська", value: "uk", flag: "ua" },
  { label: "Magyar", value: "hu", flag: "hu" },
  { label: "ไทย", value: "th", flag: "th" },
  { label: "فارسی", value: "fa", flag: "ir" },
  { label: "বাংলা", value: "bn", flag: "bd" },
  { label: "ਪੰਜਾਬੀ", value: "pa", flag: "in" },
  { label: "தமிழ்", value: "ta", flag: "in" },
  { label: "తెలుగు", value: "te", flag: "in" },
  { label: "मराठी", value: "mr", flag: "in" },
  { label: "اردو", value: "ur", flag: "pk" },
  { label: "Filipino", value: "tl", flag: "ph" },
  { label: "Kiswahili", value: "sw", flag: "tz" },
  { label: "አማርኛ", value: "am", flag: "et" },
  { label: "Azərbaycan", value: "az", flag: "az" },
  { label: "Euskara", value: "eu", flag: "es" },
  { label: "Беларуская", value: "be", flag: "by" },
  { label: "Български", value: "bg", flag: "bg" },
  { label: "Català", value: "ca", flag: "es" },
  { label: "Hrvatski", value: "hr", flag: "hr" },
  { label: "Eesti", value: "et", flag: "ee" },
  { label: "ქართული", value: "ka", flag: "ge" },
  { label: "ગુજરાતી", value: "gu", flag: "in" },
  { label: "Íslenska", value: "is", flag: "is" },
  { label: "ಕನ್ನಡ", value: "kn", flag: "in" },
  { label: "Қазақ тілі", value: "kk", flag: "kz" },
  { label: "Latviešu", value: "lv", flag: "lv" },
  { label: "Lietuvių", value: "lt", flag: "lt" },
  { label: "Македонски", value: "mk", flag: "mk" },
  { label: "മലയാളം", value: "ml", flag: "in" },
  { label: "Malti", value: "mt", flag: "mt" },
  { label: "Монгол", value: "mn", flag: "mn" },
  { label: "नेपाली", value: "ne", flag: "np" },
  { label: "Српски", value: "sr", flag: "rs" },
  { label: "සිංහල", value: "si", flag: "lk" },
  { label: "Slovenščina", value: "sl", flag: "si" },
  { label: "Cymraeg", value: "cy", flag: "gb" },
  { label: "ייִדיש", value: "yi", flag: "il" },
  { label: "Afrikaans", value: "af", flag: "za" },
  { label: "Shqip", value: "sq", flag: "al" },
  { label: "Հայերեն", value: "hy", flag: "am" },
  { label: "Esperanto", value: "eo", flag: "un" },
  { label: "Galego", value: "gl", flag: "es" },
  { label: "Kreyòl Ayisyen", value: "ht", flag: "ht" },
  { label: "Irish", value: "ga", flag: "ie" },
  { label: "Latina", value: "la", flag: "va" },
  { label: "Lëtzebuergesch", value: "lb", flag: "lu" },
  { label: "Malagasy", value: "mg", flag: "mg" },
  { label: "Māori", value: "mi", flag: "nz" },
  { label: "Samoan", value: "sm", flag: "ws" },
  { label: "Gàidhlig", value: "gd", flag: "gb" },
  { label: "Sesotho", value: "st", flag: "ls" },
  { label: "Shona", value: "sn", flag: "zw" },
  { label: "Sindhi", value: "sd", flag: "pk" },
  { label: "Somali", value: "so", flag: "so" },
  { label: "Tajik", value: "tg", flag: "tj" },
  { label: "Uzbek", value: "uz", flag: "uz" },
  { label: "Xhosa", value: "xh", flag: "za" },
  { label: "Yoruba", value: "yo", flag: "ng" },
  { label: "Zulu", value: "zu", flag: "za" }
];
